### ISSUE TITLE
download_url() only handles GET requests, not POST requests

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/data-services-helpers#12]
Would be great if we could make POST requests via download_url().

It doesn't look that complicated to implement. My (naive) approach would be to add another parameter to `download_url`; `requests_method` which defaults to `'get'` but can also be `post`, pass this from `download_url` into both `_download_with_backoff` and `_download_without_backoff`, then around line 144:

    if requests_method == 'get':
        response = requests.get(url, **kwargs_copy)
    elif requests_method == 'post':
        response = requests.post(url, **kwargs_copy)

We might also need to modify `install_cache` to optionally cache POST requests. Perhaps it also makes sense to have a differently named wrapper function for this, rather than directly calling `download_url()`.

Comments welcome!

**Comment by djui** [comment]
Closed via fd65b551ddb1ae5ebdc434d12c7b75bb193166e7
