### ISSUE TITLE
URLs with params not being checked correctly in _url_in_cache

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/data-services-helpers#19]
Needs investigating. Spotted by @scraperdragon and myself while working on GDS AAIB stuff. Switched to `requests.get` and it worked.

**Comment by djui** [comment]
This should be resolved by https://github.com/scraperwiki/data-services-helpers/commit/fd65b551ddb1ae5ebdc434d12c7b75bb193166e7 and https://github.com/scraperwiki/data-services-helpers/commit/0b37fbcc3c5d0b3d200acce262d5b26b9d77c00f.
