### ISSUE TITLE
Not Python 3 compatible

### ISSUE THREAD

**Issue by StevenMaude** [scraperwiki/data-services-helpers#23]
Running `dshelpers.py` through `2to3`, it doesn't look hard to fix. The only problem is making [scraperwiki-python](https://github.com/scraperwiki/scraperwiki-python/issues/81) Python 3 compatible first as this is a blocker. The other dependencies already support Py3.

**Comment by paulfurley** [comment]
Sorry. Just... sorry.

**Comment by StevenMaude** [comment]
@paulfurley ;) It's more a problem with `scraperwiki-python` than anything else.

**Comment by drj11** [comment]
I think it takes considerable prescience to get a clean run through `2to3` on the first try.

**Comment by paulfurley** [comment]
BTW I find that things like `urlparse`, `StringIO` etc are most easily "ported" by using the [six](https://pythonhosted.org/six/) package, which I understand basically provides a consistent namespace for both versions and wraps the underlying functions / objects. YMMV.

**Comment by StevenMaude** [comment]
See #27; should be almost there now as all the tests pass in 2.7 and 3.4.

`python-modernize` did a decent job. The issues that `python-modernize` didn't handle were handling old str as bytes and a case where `e.message` was being used; the modern way is to do a str(e) to get the text of your exception.

**Comment by StevenMaude** [comment]
Fixed by #27.
